services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cybricdb
      POSTGRES_USER: cybric
      POSTGRES_PASSWORD: cybricpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: 'D:\CybricHQ\CybricHQ\Backend\CybricHQ'
    env_file:
      - 'D:\CybricHQ\CybricHQ\Backend\CybricHQ\.env'
    ports:
      - "8000:8000"
    volumes:
      - 'D:\CybricHQ\CybricHQ\Backend\CybricHQ:/app:cached'
    depends_on:
      - db
      - redis

  worker:
    build:
      context: 'D:\CybricHQ\CybricHQ\Backend\CybricHQ'
    env_file:
      - 'D:\CybricHQ\CybricHQ\Backend\CybricHQ\.env'
    command: ["celery", "-A", "CybricHQ", "worker", "-l", "info"]
    depends_on:
      - backend
      - redis
    volumes:
      - 'D:\CybricHQ\CybricHQ\Backend\CybricHQ:/app:cached'

  frontend:
    build:
      context: 'D:\CybricHQ\CybricHQ\frontend'
    env_file:
      - 'D:\CybricHQ\CybricHQ\frontend\.env'
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
